### ISSUE TITLE
Alloc warning & crash on resize

### ISSUE THREAD

**Issue by floatingmountain** [StarArawn/harmony#16]
Hey,
I noticed some issues running the examples. I know the crate is really young, but I guess it wont hurt.
On startup of hello-cube & hello-world I get the following Warnings:
```
[harmony\src\graphics\material\hdr.rs:63] image_data.len() = 33554432
[harmony\src\graphics\material\hdr.rs:64] (w * h) * (4 * 4) = 134217728
[2020-04-19T21:27:32Z WARN  gfx_memory::heaps] Unable to allocate 134217728 with Linear: TooManyObjects
Calculating cubemap for: venice_sunrise_4k.hdr
```
It runs, but the skybox is blurry. Don't know if it's supposed to be that way.

And on window-resize it crashes while spamming:
```
[2020-04-19T21:36:13Z WARN  wgpu_core::swap_chain] present failed: OutOfDate
[2020-04-19T21:36:13Z WARN  wgpu_core::swap_chain] acquire_image() failed (OutOfDate), 
reconfiguring swapchain
```
Win10 with latest harmony. Ran with --release. 

Harmony is exactly what I was looking for and I'm excited to start playing around with it! Great work!

**Comment by floatingmountain** [comment]
Well I guess you wouldn't resize the window like this anyway. So adding `.with_resizable(false)` to the `WindowBuilder`should do the trick for now?

**Comment by StarArawn** [comment]
@floatingmountain
Thanks for a great first issue! Currently resizing the window isn't supported, but it definitely should be!  The too many objects warning can be safely ignored for now according to the wgpu devs. 

As far as the skybox goes it has a static 512x512 per cubemap face size which is why it tends to be a bit blurry. This is soon to change as I'm currently in the process of rewriting a large portion of the skybox and image stuff in the library to be a bit more configurable and dynamic.

**Comment by StarArawn** [comment]
https://github.com/StarArawn/harmony/pull/17
Should fix low-res sky-boxes! 🎉

**Comment by StarArawn** [comment]
@floatingmountain 
Fixed up window resizing please let me know if you see any issues!

**Comment by floatingmountain** [comment]
Awesome! 
I guess the gui frame needs resizing, too? Resizing the hello-world example stretches the text and eventually it vanishes.
And when resizing to zero window size it crashes. That includes minimizing the window. #https://github.com/rust-windowing/winit/issues/208 explains the issue.
Let me know if you need help with anything!
